# Generated by Django 4.2 on 2023-04-28 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagetotext', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
